apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${{values.name}}
  namespace: ${{values.namespace}}
  labels:
    app: ${{values.name}}
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ${{values.name}}
  template:
    metadata:
      labels:
        app: ${{values.name}}
        version: v1
    spec:
      containers:
      - name: ${{values.name}}
        image: nginx:latest
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 250m
            memory: 256Mi
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5