apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: terraform-module-template
  title: "Terraform Module"
  description: "Plantilla para crear un módulo de Terraform estandarizado"
spec:
  owner: cloud-team
  type: infrastructure
  steps:
    - id: fetch
      name: Esqueleto de Terraform
      action: fetch:template
      input:
        url: ./skeletons/terraform
        values:
          module_name: ${{ parameters.moduleName }}
    - id: publish
      name: Repo de Terraform
      action: publish:github
      input:
        repoUrl: github.com/org/terraform-${{ parameters.moduleName }}
