apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: ${{values.app_name}}-${{values.app_env}}

resources:
- manifests/namespace.yaml
- manifests/deployment.yaml
- manifests/service.yaml
- manifests/ingress.yaml

commonLabels:
  app: ${{values.app_name}}
  environment: ${{values.app_env}}
  managed-by: kustomize

namePrefix: ${{values.app_name}}-

images:
- name: nginx
  newTag: "1.21-alpine"