apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ${{values.app_name}}-${{values.app_env}}
  namespace: argocd
  labels:
    app.kubernetes.io/name: ${{values.app_name}}
    app.kubernetes.io/component: argocd-application
    environment: ${{values.app_env}}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: ${{values.app_name}}-project
  
  source:
    repoURL: https://github.com/Portfolio-jaime/${{values.app_name}}
    targetRevision: HEAD
    path: deploy/${{values.app_env}}
    
  destination:
    server: https://kubernetes.default.svc
    namespace: ${{values.app_name}}-${{values.app_env}}
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
        
  revisionHistoryLimit: 10
  
  ignoreDifferences:
  - group: apps
    kind: Deployment
    jsonPointers:
    - /spec/replicas