apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: argocd-app-template
  title: "ArgoCD GitOps Application"
  description: "Plantilla para crear una aplicación GitOps con ArgoCD basada en el patrón del repositorio GitOps"
spec:
  owner: sre-team
  type: infrastructure
  
  parameters:
    - title: Application Information
      required:
        - name
        - description
        - project
        - namespace
      properties:
        name:
          title: Application Name
          type: string
          description: Name of the ArgoCD application
          pattern: '^([a-zA-Z][a-zA-Z0-9]*)(-[a-zA-Z0-9]+)*$'
        description:
          title: Description
          type: string
          description: Description of the application
        project:
          title: ArgoCD Project
          type: string
          description: ArgoCD project name
          default: kubeops
          enum:
            - kubeops
            - default
        namespace:
          title: Target Namespace
          type: string
          description: Target Kubernetes namespace for deployment
          default: kubeops
        manifest_path:
          title: Manifest Path
          type: string
          description: Path to Kubernetes manifests in repo
          default: Kubernetes
        auto_sync:
          title: Enable Auto Sync
          type: boolean
          description: Enable automated synchronization
          default: true
        self_heal:
          title: Enable Self Heal
          type: boolean
          description: Enable self-healing for the application
          default: true

  steps:
    - id: fetch
      name: Fetch Base
      action: fetch:template
      input:
        url: ./template
        values:
          name: ${{ parameters.name }}
          description: ${{ parameters.description }}
          project: ${{ parameters.project }}
          namespace: ${{ parameters.namespace }}
          manifest_path: ${{ parameters.manifest_path }}
          auto_sync: ${{ parameters.auto_sync }}
          self_heal: ${{ parameters.self_heal }}
          
    - id: publish
      name: Publish
      action: publish:github
      input:
        description: ${{ parameters.description }}
        repoUrl: github.com?owner=Portfolio-jaime&repo=${{ parameters.name }}
        protectDefaultBranch: false
        repoVisibility: public
        
    - id: register
      name: Register
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps['publish'].output.repoContentsUrl }}
        catalogInfoPath: "/catalog-info.yaml"

  output:
    links:
      - title: Repository
        url: ${{ steps['publish'].output.remoteUrl }}
