apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${{values.app_name}}
  namespace: ${{values.app_name}}-${{values.app_env}}
  labels:
    app: ${{values.app_name}}
    version: "1.0.0"
    environment: ${{values.app_env}}
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: ${{values.app_name}}
  template:
    metadata:
      labels:
        app: ${{values.app_name}}
        version: "1.0.0"
        environment: ${{values.app_env}}
    spec:
      containers:
      - name: ${{values.app_name}}
        image: nginx:1.21-alpine
        ports:
        - containerPort: 80
          name: http
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
        env:
        - name: ENV
          value: "${{values.app_env}}"
        - name: APP_NAME
          value: "${{values.app_name}}"