apiVersion: v1
kind: Namespace
metadata:
  name: ${{values.app_name}}-${{values.app_env}}
  labels:
    name: ${{values.app_name}}-${{values.app_env}}
    environment: ${{values.app_env}}
    project: ${{values.app_name}}
    managed-by: backstage