apiVersion: v1
kind: Service
metadata:
  name: ${{values.app_name}}-service
  namespace: ${{values.app_name}}-${{values.app_env}}
  labels:
    app: ${{values.app_name}}
    environment: ${{values.app_env}}
spec:
  selector:
    app: ${{values.app_name}}
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    name: http
  type: ClusterIP