apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: terraform-module-template
  title: "Terraform Module"
  description: "Plantilla para crear un módulo de Terraform"
spec:
  owner: cloud-team
  type: infrastructure
  
  parameters:
    - title: Module Information
      required:
        - module_name
        - description
      properties:
        module_name:
          title: Module Name
          type: string
          description: Name of the Terraform module
          pattern: '^([a-zA-Z][a-zA-Z0-9]*)(-[a-zA-Z0-9]+)*$'
        description:
          title: Description
          type: string
          description: Description of the Terraform module

  steps:
    - id: fetch
      name: Fetch Base
      action: fetch:template
      input:
        url: ./template
        values:
          module_name: ${{ parameters.module_name }}
          description: ${{ parameters.description }}
          
    - id: publish
      name: Publish
      action: publish:github
      input:
        description: ${{ parameters.description }}
        repoUrl: github.com?owner=Portfolio-jaime&repo=${{ parameters.module_name }}
        protectDefaultBranch: false
        repoVisibility: public
        
    - id: register
      name: Register
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps['publish'].output.repoContentsUrl }}
        catalogInfoPath: "/catalog-info.yaml"

  output:
    links:
      - title: Repository
        url: ${{ steps['publish'].output.remoteUrl }}
