apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{values.component_id}}
  description: ${{values.description}}
  annotations:
    github.com/project-slug: Portfolio-jaime/${{values.component_id}}
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  lifecycle: experimental
  owner: devops-team
