apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  labels:
    app: ${{values.app_name}}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ${{values.app_name}}
  template:
    metadata:
      labels:
        app: ${{values.app_name}}
    spec:
      containers:
      - name: app
        image: nginx:latest
        ports:
        - containerPort: 8080
        env:
        - name: ENV
          value: base
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"