apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: k8s-deployment-template
  title: "Kubernetes Deployment"
  description: "Plantilla para crear manifiestos Kubernetes básicos"
spec:
  owner: sre-team
  type: infrastructure
  steps:
    - id: write
      name: Crear deployment
      action: fs:write
      input:
        path: ./deployment.yaml
        content: |
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: ${{ parameters.appName }}
          spec:
            replicas: 2
            selector:
              matchLabels:
                app: ${{ parameters.appName }}
            template:
              metadata:
                labels:
                  app: ${{ parameters.appName }}
              spec:
                containers:
                  - name: ${{ parameters.appName }}
                    image: ${{ parameters.image }}
                    ports:
                      - containerPort: 8080
