apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: go-service-template
  title: "Go Microservice"
  description: "Template for microservice in Go"
spec:
  owner: dev-team
  type: service

  parameters:
    - title: Fill in some steps
      required:
        - component_id
        - description
        - environment
      properties:
        component_id:
          title: Component name
          type: string
          description: Provide a component (microservice) name
          pattern: '^([a-zA-Z][a-zA-Z0-9]*)(-[a-zA-Z0-9]+)*$'
        description:
          title: Description
          type: string
          description: Description of the Go microservice
        environment:
          title: Environment
          type: string
          description: The environment where this component will be deployed
          enum:
            - DEV1
            - PROD1
            - UAT1
            - SIT1
          enumNames:
            - 'Development (dev1 namespace)'
            - 'Production (prod1 namespace)'
            - 'User Acceptance Test (uat1 namespace)'
            - 'System Integration Test (sit1 namespace)'

  steps:
    - id: fetch-base
      name: Fetch Base
      action: fetch:template
      input:
        url: ./template
        values:
          app_name: ${{parameters.component_id}}
          app_env: ${{parameters.environment}}
          description: ${{parameters.description}}

    - id: publish
      name: Publish
      action: publish:github
      input:
        description: ${{ parameters.description }}
        repoUrl: github.com?owner=Portfolio-jaime&repo=${{parameters.component_id}}
        protectDefaultBranch: false
        repoVisibility: public

    - id: register
      name: Register
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps['publish'].output.repoContentsUrl }}
        catalogInfoPath: "/catalog-info.yaml"

  output:
    links:
      - title: Repository
        url: ${{ steps['publish'].output.remoteUrl }}