apiVersion: v1
kind: Service
metadata:
  name: ${{values.name}}
  namespace: ${{values.namespace}}
  labels:
    app: ${{values.name}}
    # Backstage Kubernetes identification label
    backstage.io/kubernetes-id: ${{values.name}}
spec:
  selector:
    app: ${{values.name}}
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  type: ClusterIP