apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ${{values.app_name}}-${{values.app_env}}
  namespace: argocd
  labels:
    app: ${{values.app_name}}
    environment: ${{values.app_env}}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  
  source:
    repoURL: https://github.com/Portfolio-jaime/${{values.app_name}}
    targetRevision: HEAD
    path: k8s/overlays/${{values.app_env}}
  
  destination:
    server: https://kubernetes.default.svc
    namespace: ${{values.app_name}}-${{values.app_env}}
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
    
  revisionHistoryLimit: 10